version: '3'
services:
  nginx:
    build:
        context: .
    volumes:
        - ./auth0.conf.template:/etc/nginx/templates/auth0.conf.template:ro
        - /etc/certs:/etc/certs:ro
        - ./http.conf:/etc/nginx/http.conf:ro
        - ./modules.conf:/etc/nginx/modules.conf:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:443
