version: '3'
services:
  nginx:
    build:
        context: .
    env_file:
        - .env
    ports:
      - 443:443
    volumes:
        - ./auth0.conf.template:/etc/nginx/templates/auth0.conf.template:ro
        - ./cert.pem:/etc/certs/cert.pem:ro
        - ./key.pem:/etc/certs/key.pem:ro
